### ISSUE TITLE
在vue框架使用中出现跨域问题改如何解决？

### ISSUE THREAD

**Issue by dawnFlyme** [WeChatAI/openai-sdk#2]
` Access to fetch at 'https://openai.weixin.qq.com/openapi/nlp/sensitive/xxxxx' from origin 'http://localhost:9127' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
request.js:150 POST https://openai.weixin.qq.com/openapi/nlp/sensitive/xxxxx net::ERR_FAILED`

**Comment by zhang-ning** [comment]
已支持跨域
